### ISSUE TITLE
Add types (for Glint)

### ISSUE THREAD

**Issue by BoussonKarel** [RobbieTheWagner/ember-math-helpers#1160]

**Comment by RobbieTheWagner** [comment]
@BoussonKarel this addon should be fairly easy to convert to TS and glint. I'll see if I can find time to do so soon.

**Comment by BoussonKarel** [comment]
I've started working on it on my fork. I just need to test it.

**Comment by BoussonKarel** [comment]
https://github.com/RobbieTheWagner/ember-math-helpers/pull/1162
