### ISSUE TITLE
Namespace '"@ember/component/helper"' has no exported member 'EmptyObject'.

### ISSUE THREAD

**Issue by jelhan** [RobbieTheWagner/ember-math-helpers#1220]
I run into the following type error when using ember-math-helpers with types provided by Ember natively.

```
node_modules/ember-math-helpers/declarations/helpers/sub.d.ts:21:50 - error TS2694: Namespace '"@ember/component/helper"' has no exported member 'EmptyObject'.

21         Named: import("@ember/component/helper").EmptyObject;
                                                    ~~~~~~~~~~
```

I'm using the following versions:

* ember-math-helpers 4.0.0
* ember-source: 5.4.0
* typescript: 5.2.2
* @glint/core: 1.2.1

**Comment by jelhan** [comment]
@RobbieTheWagner I'm using the types shipped with Ember 5.4. I assume you are using types from DefinitelyTyped with Ember 3.28. That may explain the difference.

**Comment by jelhan** [comment]
I don't have a computer at hand the next days. I can setup a reproduction mid December if that helps.

**Comment by jelhan** [comment]
It seems that this is caused by how TypeScript compiles the helper signature.

We are having the following code: https://github.com/RobbieTheWagner/ember-math-helpers/blob/bb1cebcd5f6c33ec9de427fcce2433eaefb8a743/ember-math-helpers/src/helpers/sub.ts#L3-L8

TypeScript compiles it to:

```ts
declare const _default: import("@ember/component/helper").FunctionBasedHelper<{
    Args: {
        Positional: number[];
        Named: import("@ember/component/helper").EmptyObject;
    };
    Return: number;
}>;
```

Please note that we don't declare the `Named` property ourselves at all. It seems that it is inherited from somewhere else and than inlined by TypeScript compiler. I think it is coming from `@types/ember__component`. Especially from this lines of code: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0bd89f8e13fe2f9ad930c5255863d85daaff073d/types/ember__component/helper.d.ts#L23-L39

Sadly, this is not the first incompatibility I'm running into between `@types/ember*` and types published by `ember-source`. I don't think it can be fixed in this addon but needs to be fixed upstream in `@types/ember*`.

**Comment by glenn-vandeputte** [comment]
I'm running into the same issue. Is there a good workaround to acknowledge this failure until the PR which fixes this is actually released?
