### ISSUE TITLE
warning: export 'default' not found in 'ember-math-helpers/index'

### ISSUE THREAD

**Issue by michaelchadwick** [RobbieTheWagner/ember-math-helpers#1868]
🐞 **Description**
As of version 4.1.0 (4.1.1 and 4.2.0 are both affected, too), running `ember serve` on an Ember app with this addon installed gives a warning:

```
WARNING in ../../../../ember-math-helpers/dist/_app_/index.js 1:0-51
export 'default' (reexported as 'default') was not found in 'ember-math-helpers/index'
(possible exports: abs, acos, acosh, add, asin, asinh, atan, atan2, atanh, cbrt, ceil, 
clz32, cos, cosh, div, exp, expm1, floor, fround, gcd, hypot, imul, lcm, log10, log1p, 
log2, loge, max, min, mod, mult, pow, random, round, sign, sin, sqrt, sub, sum, tan, 
tanh, trunc)
```

🔬 **Reproduction**
```
git clone <repository-url>
cd ember-math-helpers
pnpm install
cd test-app
ember serve
```

🌎 **Environments Tested**
```
ember-cli: 6.0.1
node: 18.20.5
os: darwin arm64
```

Also tried in two existing Ember apps, both with the same environment:
```
ember-cli: 5.9.0
node: 20.12.2
os: darwin arm64
```

**Comment by RobbieTheWagner** [comment]
@michaelchadwick have you hit any problems using the library? I saw this warning but didn't know how to resolve. It still seems to all work.

**Comment by RobbieTheWagner** [comment]
@michaelchadwick I think this should fix it? https://github.com/RobbieTheWagner/ember-math-helpers/pull/1872

**Comment by michaelchadwick** [comment]
@RobbieTheWagner I tried your fix and the warning went away! It didn't seem to affect the usage of the addon, but nice to remove it.
